# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
# Setup for Yantrashala
# Version : 0.0.1
# Author/Contributor : Vichu1988
# Last Updated Date: 30-May-2016

# Site settings
title: Yantrashala
title_title: Yantrashala | open source initiatives
name: Sapient Nitro
#email: Visweshwaran.s@gmail.com
location: Bengaluru,India # ex. Nice, France
company: SapientNitro
company_url: www.sapientnitro.com
github_url: https://github.com/yantrashala
#P.S icon
#company_brand_icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAHO0lEQVR42u3ae1BUVRzA8fKevcuyrIDi1NSCO8ZM6oIBm00KCI6Nr6kEEwtSpHGy8RGmokZDxR9NsCjg4w//sTGfpTJoZYKoASL5wBeCiQ8eiQlaoCBOPpLtHGI5IO7vd67LtttMd+Y3I7Pcw/189+5lvctT/299vFkslqdlWQ5QqVQjTSaTyp61fHx8dISQMI1G4/efwOt0Oh+JkIP9JMnSMYScZzGeZC1JkqLoGk2da7XTr9fGxMRILo2n4PIuPJ8bSiNIsjyd7vfXo2vRCNtYBJfHoxFw/AO+LxbB+fiBHA/OdRrBqAQPRNjKIzgffwbF94ww3MZrPgbAAxFcGo9HwPF4BFfEP6TTBjzeSCMM68RPQ/CtIhFcCr/M9MqhbRMmlyMH30jXSYLwbhp1dcnxlIbgEEMxEmFLampqP4fj+/fvP4Ae9GkEX3I14X0LGywCGwh/uCyl8eKVDMul+hXtNEKRSASn4pfSZ96KhyOI49lYIwQFo2fCZhbBKfik3ngeYfxk9pK5LYJXa9Q13fG9I/g5IAKOPyWKRyK0gXg3dW13vK0II4LQCJt4BMfi2xeHjOR4YNJHhx2h338fPHBCbvxQsLiag+2P4BJ4c+gYjkdGUpHre/aLRQgc4XvIIRE8PT29Kf4khF8UYnoivBMibGQRXBCPR6Avhxo8QsZDo3gE+/EfBYvhM0LHHIXwallVu/TV4YehCyNRECFghB67JnzNIzgbr1LV7YsZe+1MwkTLmtdM7DpzRyQCPOaHxkD9IYUROF4i5ASEXxj8crEIfoUCvHVWjTOdxiL8eGBJtUiE4XiEDZ0R+D08ii+E8InBIULP/MowpXg+q8ehZ0IjjVDTFxEIIV90BaBfjHUeXnmEvJ+SxCIYny8BXPcNBoOb9S7M27a+USakviJuZrO9eDaRg58tZEhoTiZMuO/trrG+5QYiLKnFImzdOfccv6/Ye9zd3Z/rCMD+AV2JtWp1FRQhKyyS45GJftG3CMLrPXVHRdYhMmmAImzfNf8XiUg3ba5BSPmj9+Ji2Xt6Wzt40AiVcfHNNvD3gIMFIuB4PEJSnTCeT5Msy4G978mpVPFKImSFRxwD8OBMHTq4qDve11N3hD+uKMK1/MKldQrwzSqVKpirnzAChpfpBc/LXXsaiyCCH6IfWMoujFCEgsJldYL4EKsVijALiuAmy9UI/tcdU+N+K3h39h1vrfYUhNOo5QvQ46FBhsKKnEWWtR9POYVFoPhmUbzdETB88cw5FjYFcbPbvN2hCDjeOmuWv3kSimAXHo+gHG9PhFFBhiKORyLgeBPARCMk8AgI/q3YqxzeO4KXYIRRL/Fn/rERlsERcLzyT2nXID+ofd2kqCoGhWZv7HvsAnULWsvbS3uGIbGJjxpZhAVgH7P1BX4y/KuOv1naMz3hpi184Yw5D/TeA4R+1U0bH1QE4bemxVZJEr/gAXNVrVb724u/yxdEI5znEXri/bwH/KzkGhBjI8K29DiGb1KwVj2N8IID8FgEjvcFnnkwwsSeEb41w3g8gjh+EsNDd27Z6x6LAOL5Wtehx6fTCIL4W3T+xCLYjZfV6vqcktL6WYkLi+EIbuf1CD4kILD4wObtrfRmDPi3BaPpr0QM/31Gxrn1ycknRCLYjS+tu2Jhg0VA8EWlO3db2BzcsgONgOGb8vZa2Hz1SXIZEuGKm5vbkF54QsgECE8ofmdxSRceiiCO5wOcCQjeXGnFd0VIFopg6Pn3PfwUQ/H2RAg2BnD84yLogAgons/65OVgBImQw91P/Wk28bLcAOF5hEQ0QuDQYcVWLBTBw8PjHIb/zpzO8UAE6I6QVqt9puv0B37YvZTMzGMAXjgCg+3f9M0tKMAGc+YFiZA/gONp2W02VzAgNq+HhhZCH+gOGjTIoyMA+2tO9hkgGGFl5nGRCPELxCI4Dc9vja+jdL5pNBo9feDyvxNBV/lohA0ZWRcp/ncQn55W2Sd4Qvb6+/urmVtxhE8zs/skgu6fCC2i+F1paRWOwDs0woz589EI2Smp5X2FfyMsTBEeiuBLd6h2QARgHI7PQ/DKI6RkZpeJRJg5b0ERi6AYn552VgQ/JTzcDry9Z0L2KrEzYd48JRFaHYV3boS5QhFac9O+LBfBR+H4fBgvHsGPLlhjb4SN+fmXsFtiHlptVW1OTguKj8Dx1g8/+ebgCJ9lrSqD8J33ESzYeOl0lVCE6IgIRXjnRcDxeATl+H0w3vER7n6ezSNszMu/DODRCHW5uS1OwMMb/b/0YPoDa7EIm/L2YfjbhJDVIhGiIyOV4p0fgb3DQ/BhbK1+KtWH8CfA8jUEXwDgnRcBxfONRUjE98PxLhYBxwMRXAyPR6gTxIfzPYEIOH6/Xq/X8D2dH8GARGgD8EAEHO+iEXA8HgHHu2YEQs52O+gGAI9F+KDjVj3H53K8C29Go1Gm6ImSJEV70c3eN16SLL9D1xvlqOP9G+vcHotWNz/hAAAAAElFTkSuQmCC
#Nitro icon
company_brand_icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAA2hpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMy1jMDExIDY2LjE0NTY2MSwgMjAxMi8wMi8wNi0xNDo1NjoyNyAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0UmVmPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VSZWYjIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDo1MUJDRkU3ODA3MjA2ODExODA4MzgwNzEzMjA4RTk4MSIgeG1wTU06RG9jdW1lbnRJRD0ieG1wLmRpZDo2REVDQTUzOEIyNEMxMUU1OTE3NUVENUJBQUJGMTg1MCIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLmlpZDo2REVDQTUzN0IyNEMxMUU1OTE3NUVENUJBQUJGMTg1MCIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ1M2IChNYWNpbnRvc2gpIj4gPHhtcE1NOkRlcml2ZWRGcm9tIHN0UmVmOmluc3RhbmNlSUQ9InhtcC5paWQ6NTFCQ0ZFNzgwNzIwNjgxMTgwODM4MDcxMzIwOEU5ODEiIHN0UmVmOmRvY3VtZW50SUQ9InhtcC5kaWQ6NTFCQ0ZFNzgwNzIwNjgxMTgwODM4MDcxMzIwOEU5ODEiLz4gPC9yZGY6RGVzY3JpcHRpb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ9InIiPz71w2qmAAAFFElEQVR42uycXWgcRRzAdzZ7G4SEpKBVS9qgVmm9u00uBwpG4axf5ElBiooQEYrgQxHqc2tUEEGloFXogygWArZK+hZ8KPoSomISkrurDxWpButHDpEoeLnc7vjf5B6C5MGbRJLZ/f3g7nb37j/H7Px2Pm7mVmmtHUgvLqcAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAHABjzbM6CU2pZ0stnsqCT1rNa6KLsZSdmV/bULRI6F8j1N2fxN9j7r7Lzu5MzMTK31nt3nz/oMbIMAuVzuba2j422EXPO8zF3z8/M/2X7+Ut8EBEH2SJuFH7MvDJtn6QMkgChyHjcMfWRwcLAXASxHavBDZnHaazabBxDAfgUyxifPdT0EAARIb/OhFQJYj1LUAIAAdAKNaCCA9Q2A6jP9CaGrq+s7BLCYfD5/q3Tk9hmKc3F6evpvBLC6Fx+9GJelQeF/n8n4JxJRA6Z1Mkiu/kejKJzYRIAVSTOK/Vgf6cWvMt5bP1aT/U98339rbm5uqTUUtPr8eWm76ovFYk+9Xj8uV/9LGwr/iuuqMc/zv5CCvZaqPlBSaoCBgey9zaYzqpS+RY52tApXHlryGL/GH9R75NhBeXRuiP/48GFn9MKFqlGPnvUAuyAPuVzuTSmKE+3L48zu399/z+Tk5Ip5PwIBdpSBgdxTYajHDbP/TLVa/WhrHUkWhOwoUvgvmMb29vZOpP13kCQMA+80jKtPTU39iQD2023YeQwd4KdgBLAf016YovhTXANI753aL+VNADVAypsASIIA0ptfMgz1h4eHuxHAfj41dWd5eXkIAexvyl+Xp5/NOoLhMQSwnEqlsui6HUdk81L7AjhP5/P5B9MsQKIWhBQKhRsajcYdcfv+7891dMR5dW6KIudhCXlM8t3TemtFUnlORDonaen2JWI2cNcI8F8JgqAvisJzkvfShnQW5fmibP669pfR9WNrq4JkL14RJI/oqud1Tm1cNIIAFgoQMzIy0rm4+MM3kv1cm6F1pdxTUmO8gQAWC9CqCe4Ow+aXZt/rHhMJ3mc9gMUsLCx8JQL9YTaCiE4yCkgG84Zx/UND2YMIYD/Gi0JWV90eBEjAUDjNmUcARyNAqotfKxcB0lz/K5oA+gAIkGr2mAZ6nldDAPu53azpUEuzs7M/IoDFBEHwgNa610wA5xWT2UME2CUcPZr1oyh81eDKbyrlvlwuV88kogOUxsmgUinbVas5H0reN9wnWP0uF/Qleb3qbHLzJ/ma+ET94nn+BNPBu1SA9YJVh+RYZvMxv77ZcaK8RD0v2ze24lcliVN9fQdOm/xNHAF2gQCFQqF/dbVxVvLyUJvNmpbq/MlKpXLe9Pu5RcwOUywWr19ZqX8tBbG3fXnc8a0UfhKwXoB6vf6aXId7DcPfS/sYOAmjgPu30Hx8iwDWo28zjfR9/y8ESMBQ1jSwu7tbIwAggO1tAMVIDQAIAGkVwOgun/GkTqlUihDA9iGAUrNGHQety2NjYwhgvwDOu0YZd513aAASIEC5XB0XDU63qc2ZcvnyBxR/gqaDgyC4LwzDJ2Q3vj9AZpMqP5T3rmitzler1c+3bQzKdDDQBAACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAsD/zD8CDADWhbx8vuXgyAAAAABJRU5ErkJggg==
description: Sapient Nitro's yantrashala page. This page is an entry point to our open source contributions.
favicon: favicon.ico # Image must be in assets/images

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
url: http://yantrashala.github.io

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

#Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

syntax_highlighter_opts:
  input: GFM
  syntax_highlighter: coderay

#Nav-bar
# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: Home
#  -
#    href: /blog
#    label: Blog
  -
    href: http://www.sapientnitro.com
    label: About
    target: _blank
