# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Building Tools for an Open Source journey to Microservices for the Enterprise. # ex. I m Chuan
name: Yantrashala # ex. DONGChuan
email: my_email_address@lalala.com
location: My location # ex. Nice, France
company: MyCompany
company_url: my_company_website
github_url: yantrashala # ex. https://github.com/DONGChuan
description: description_of_your_web_site
favicon: favicon.png # Image must be in assets/images
logo: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQQAAAEECAQAAABkAYKBAAAU0ElEQVR42u2dd5wURdqAn9plA2mBVRHFLB/BgIqYDlHxPH9wgH5mzOEUzGAgmEAwAcohoocYPuVDUTwzoPAZEPXEiAr3UxE5URFJS2bj7LzfH9PALjO9TBcz09O979P/EOatqa5+pqq6uqraCIoCOX5nQMkOVAQFUBEUBxVBAVQExUFFUAAVQXFQERRARVAcVAQFUBEUBxVBAVQExUFFUIB6J0IlC+UUGSBVfmck6zD1aT7Ch/IKnyFAF25nV+N3frKJBn5nIDN8KZ9QwXTKyMcgzKEzF3hOZYksYD057MGhtDC5fp9USqkXIvwo/YlQTQEFgKGaYlp7TuULuZcNVAM5tGKMtA5VjRJ6EZbIs7xMEflA7MoJEY7gRE+XsUTuYw755GAooxXj2D1UGoRchG/lW6ZQQgu2SBDToC1/85TOcrmDr2kMQDnHMjB0GoS4s7hGpjCdP2hMLts0gCil/A+He7iQq2QI82gCQBXtGE9R6DQIcY3wMpPIo4ja10yooIsnDVbKbSxwNKhgb+4NpQahFGETG+URZtEIE6cBVHGVh7SWyQ38QkMAKjiMx0y+36eXJkIowp0yiyY0JtEPt4pDaOUhrZf4iSIMgtCSJ0NZF8QInQhPynyKyUmggSAUciYtk76cG2UqTZyUIhzp96mllZCJcL9Mw5BL4mu9mY709vCr/pgK514BcliBEN4qIUTPGkZKW3mFXBcNhDLOYJLJ85BiydbiMeTyHmF+QhGaGqFE5lFMXV25Um72+INuQ6TG3/IJ16BybUJSI2yQ4SzF/dcuVNDEuQlMnoNpQM1xls1hHXQhJCL8Q87nyzpORSjnMF7wnG5T043KrX8r5OkdfL6CS2VZQGUJhQhPUkJu3KjBFoRq9uM2DrTo6XWhyqkTDAXMqvOzS6WXLGK+34VhSQhEmCj55NWhgVBFPw6w6vDvTXTrn3PYwG+uv/dFMohNCCV+F4clARfhNxkmL9DA9bZOMGykN6dY3vcV1vizwTCG2QlVWCC38TM5FNLM7yKxJNB3DVFG8DUFdfYOSjmaOwxUsUT+y7MOq2ooZsjhM77lNenK8exRI60VchMbKCBCCw7yu1AsCfTTxw1yFC2hjkYhwtE8ZPIp536ZyK+mwOM3nCe/1LolFaJUE6GcjnTnOFqbQubJzVTRAKjgOMYFdMwpwCIslOeZSYGrBlBJZ4bR0pQxVD6imr/Qk440TfJSfS/v8GyCZxZCbJZTGbl0oCVfUumMMGzkn3ivdbKDwIrwm9zCYhq5amAo43BGUWyi3CZvU4ShHENPbk5Kha/kLpa7PLrCuZMQIggNyAEM6+nJ/QHVILCdxXIm8msdGggb6MA4U2zKGSyzaUYOhkLyeIMlSX3DO6x01SDWcTTkkE+BUxus5VSGBVaDwNYIs+SWWhPQaiJUA90ZamC53MnXNNzqu1BNLg/Tto5aoZK1Mo4ZcZNaqDHKaGr9axThUvoFWIOAilAiF7DB5aZRiNCUKznXQDn9ZP7WB8lbiLCRA3iAg1wu3EQZR2MKE2ggVBOlAblbB5lw/u06Lg60BgFtGqaxwlWDanZlOOcagHwOTPCgqAHNWcqbLmn/KrNollCDavI4klPYjbVUEHWmq1TQiP6B1yCg4wjfkKgeE6opZTUjOc65LDn05iWkRtOwhYbMoFj6xl2+JTKY5XGSCVVsAl5jH5PDOlnEl3zIfHKo5Hjuthy1zC4C2TTAffLKdl05oZJduIEecRdltLzq9OxrfloopZRbubLG57tKCUXkxWkQYS8eoE0ILrc7gWwa4GwaU12jXhAq6MDoBBrAINOdiu3qEEMOjWnO+6xx/qOcqRKlmPyEfYN7Qq5BYEVoY25CKEWIPWReQwGDOcTlYt3CairjmhNDHr9wJ78LwFx5iOqEPYP1tKJ9yDUIbNMAsImJMplGlHM0t1JMcR0X6ycZy9y4cQEBIhSzDxNMGYYTJbfWcpjYzeZtdE16NDK4BFgEgO5iKOS1JC5TBYPkswTtP0QQxnKcgbfkPqSGCtU05A66hV4CCLwI62Q5ByS56CTCUZKX4NmEUE1DBtDbwEwZxxpn6bywgW6BfYjklYCL4I235WW+STAwLURoQkfGGFgsI1hIHkI513Ks67BT2KhXIsAvMoSfEg4XRVnHldxkYJVcznKquZLr6okEUO9EgJVyFcsSqBBb+XAyQ00T4BI5kv71SIM0i/Bv8bKcZBtRmteaAZRaXpX/5Y8E4wUQJcoRDGJfs1pWprFRWCTVFmumKmjlYbmeV9IqQnNpaXHCQjlnpLWT9qMMZLmLCqW0YTT7pfHbN9FVNnpeLBOhAdPTOO0lrSLYJ/5n3k1rxbxAhrA6oQpCJbvyWBpVuFnG2sUxJo1lktaRxc+tF4m9x/A0GbpelkqEQ00/8msNUm/BkM8aLuP9NH3/kzLeKu4i7kvrTyOtIhxlFrK7Zezd3JCGS/GFXEZXRkqU08w4iogkVKEB5YzgxTR8/8PSt9Z6ymRpw2RTaBGXPGl+1nCgGWQd+ygLUnwpPpK7+Z29eIO/SzWdzO00rLGAZRuGPCr5B0+mXIWbLOM6pToj8eec/tvHTvK1ZWR7vk9pddhd1pFHrB9wL6caeFUGsnvChfRCNYYruTylObAtbkn7rWwGnj7Osz6JH3gzRZ5GeVQOk3XO0jhDHgMYL3CmeYqmLn2FXGAsfWVVivLwb7HT4LwMaJChx9A9rSOHUpKSyzBaXqDJ1kdOhhx2ZRLPCnQz15Pr0kDk0JyvGMLSFOShjOut4g5gRCoKYIdkRISJ7GoZ+S1jUvD9S2UKpta+SgahkIm8KtDbXMdqoglrBaEx33BXCvIwQeZYxR1N24yMcGZoiHmZ9OEjy9hzeGknimK1DOc/rE3QDxCqKaQ/pxt4RJ6hccIV1QJUcAT96LQTuVgkba3iWvBjhnaRz9izhoXSxXrJuH0b+btczTIKXPdVqqQV49jPwGR5gqjLbmxQTkMG0cs6H8Plbqu4xRmbGJuxqWrtTFPr2HnWtr7DrzRynfpeRTNud8YQLzYXUoYkbCAMhUQYTqllLhZbajA4g/OjMzhn8SnryNOYaqHC2zJcJsUtb9mCIOQxhGO2/vfV5nzWYxJOlY9t2XeXTLZ498t06WV11n0ZmcHnnxl9DP2MXGEZuRfve3zgMlMeYPPWlYnbI8AaxnPydmkOlpkU4baUrgLD6dzqaRven6UHC63OeTo9MyhCRmcxX24utIxcyk2Ue/j8KplOKQ1dNYhgEmgAo0wfKhM2ELFdlPKZxBxPv53XLTW4JKMaZHw6+wPWO4rM4IskL8BqeUvu4tOEk08gNhspj/4JNAC4xfSgHFxUgGKeZIb8nGReSuQDq7O9guGW5WRLxmco3Sn3WUaewJykfiMj5TkaJ3zEDLELXMYtnO+aVhnD5F2auG64W0UpHRnCwUnkpofMtDjTP/GvjM+OyvgCl2sptoz8MKku4wKZQ1EdGgiruaIODaAh95pD2UziWgHyKOI7ZieR42lWGsBkyxLaGXyYszhbelnfiC1wXc0EsEY+5kEirrusCVEi9OOKHf7eItwqn5DvumlflAou56w6X+mzRPa3OsdCltMs4zWCL5NXf5OD2GQZO4O/uhTSFzKAzTROOCgEMQ0MZ9PfJFPKK2UEX8YtiNlGlDIqGUQf122+T5QPLc6vEx/4sq7Kl7WPe5vbrWPd++DPUUVT1y36Y/cKvbguKQ2gpRlOh7jFs9vIoRHNeJSZLh/4Tn62OLsG3OfT8jqfFsHuax35mcu/V7DGtS7Ysm7hJIZ42KZ/FzOW5i6jjRAbcaxmrsvm/SP5zeLs+tLdp0n0vq1reEG8v4l1C4mePYyRKXVurhWlCw96LuRNXCOLt3tPXE2qaMHDCZ4PZu8EFDd8WxZ/vjnbOvaaBMUccT0VAaL8iREWhdyEO9jXdZahEOEg4t8Ie42lBjva/T2d+Lg/whPWX/4478QVdT7upV/BkdzmvKvNK+3N3eySYHeF2LPLUg7Z+rKfbTxv9U29k7ibSR8+itDCzLOOjZ8Sfg77JfjlCkIlezLe7GJdyO3MZCrjprNFKWdvZtMnLt1bZaPFtwzgTV+X2Pm6Y0oHc6Bl5Nu8sN1PdC+zR9zFiu1+sA+v72QRtzBTKK419V0QDudl0zJukvkzYjOnqj1jfV5p6asI+TxiGRlhBGu3U+FEhLIaMsQ2vzuAUSnIaQczaOsqCEHYyCH8PcHnVshIq/Rtp/KlDp9XQ0eYIRdjU5XCMbxOq1q/ow/kc94gunXPwHI6MzRly2kXyaXODWrsReH7JEj3CPnGIuVzuNv3fRiyYFn8eLnRMvIYPo0rvvfkHjaQS5RyzmWgaZTCnE6XWymijG484nLZbIpzD773YUg5FTnPmkzkUZmgAP+QmfxCW84wdvcJdfEfeYmDOM3lsnWXWd6SA/J5ny6+a0CsxfP7ONs6dIJs9j33sWOdjLYK/Jv4nfPY4XsGYseF1qEPZ0lB3mMVViRfZUn+fc9A7PhOWluGFsmSLCjKhZJrFTguC/IeO7Jk59UO5jHL/cE30MfvzAPzqfYck0sPbsyG3kEMv03cdnS1Dv3J59/VPKuwUVlTG2RRjQDsxHTNS33O+flWUdn1YsAsEqGbOcsy8l9M8PEueJjYTFhvS2f/spwIv6uk2sfL1qEXSNSXHN9pFdY3q5qFLGsaAE4zvS0jp/CtL7WCzcLe3ZmYPZ1EhywTIY89rWMrfcjvh/KERZQf09V3iN9V0vZHFT0tQ/NlToYr3OclxyKss1T7XsrxR1Y8a9ieRlJmF0dJmjehq4nduoViPs3K1wZnWdMQ43XLuFKuz5jXFfSzihuRlRqQfU1D7BhsGdhAbpT1GWkgnrMKe0UqfC/bADUN8LF0tY79nKPS/puLcIZMt4jzb7r6jsjKpgGO34m1UMsykL+xVhrYbbCXIfyuktyOEhlgGbqnTEtz4/CiRVCBnClVvpeq++F7Buo6/mod+mMaVZhqFXZJ1o0l1j6ytI8QY5m0tow8lVlpa417ylueY1ozL41vX0kFWdpHiNHcFFhG/h8Pp8nw1fKHRVTnLNcgy0VoxArrh7VvsjENKiyWg/G+13zHnV5ik36yWgRoZoZZZnE2j6chP3ew0iJqahpyknL87qTs+DjDOjTVgzdzrMJGZ3k3MQCdxS3YZ/I5LkxhpWyTj6EMz/pmAbK+aYgxwDoylTsOTLLQwNAx5aWRHgIhwv2mjWWk7e5t8ayQey2iruasQNQHBKGPIAgbOdMy9NSUPIRaLC0twp4JRO8gdviegWSPtbK/ZejgFFyO9hZB1wRIg6ybs+hOc9PEMnIUP+x0j/gHixj7N1n5QWBEgInsZhlpv39bDJvNsc7hmHQXSEoJxO3jFuxnKaxkN+tO21i52XPMwcw3AfqNEagaAY43d1pG2i6dgS/F5nV7c4JVsARMBLiFo63i5jJQKizi1kh/1nmOmoD9Hm5+ETARmpvzrOIiPGT1PHI+n3iOKebqwGkQsD4CQAWHyiLLWO8zBvuI9wdGU+p8G0S2ErAaAQp4y3ozOq+v9p1qocGIQGpAcAaUah4RbPdXKfEwyHOvRfovBWoQKZADSjXJtd5L4YakP/m1jE/6s9s4J5i1AQFsGmK0tIybyrtJNg9zWOE59X38K5Cdx+8qyfaYI4WWoe8lUX3Plxae030gsM1CYJsGgBPMNZaRySywvYe1HlPtxnU+l8jOEbjbx5q0lFUWUcfz0Q5a8k+ki8c0m/M2xwa2fwCB7SPEmGsV9TEn1Gn/s3Kq5zQ7B1yDgItwoDnZKu4jHqxDhSfY7DG9JrwTcA0CLgKMxm739cf4yVWFKi8JAVm6FY5HAi7CkWYGe1nE/cK0hP++QS7x+MaFfXmc/w58fRB4EeAkY7OdFcxO+MufxGTXd7ol5nT6hUCDEIgAPawuxDSeiWscVlm8QsR2fnW2EQIR4ESrqEFxG2lf5jmNU+gbivogJCK8yEUWUes5TWq+IEzwutz9ap7Gdr121uH30GZqjtVymFXgVTWGhYd6jG2X1Tug1Jsh5trsYibQ1CJu2zT1uTLWU2RTXrV8w0R2EhIR4DhzkkXUz8wVgF9loMeXDl7j+wv6UkugnzXUZqG0t4jamy/Y3XQRb3MTW/ExB4ZKhNDUCNDO2Ew8/41x4HmK6piQaRCqGgHgNJlmETWdXh4+ncNlPB0yDUInAgyQcWn+hse4NnQahKppiHEHtm+gT5YOfp9iWgidCLuZ9P5cj6aT36eYFkInAiwyNncPyXE7nxn/X+idDkLXRwD4UdqlJd32fB9KCSCUNQK0NcPSku4Uv08sjYSyRgC4Sp5KcYp/5t3Q1gchrREAjkxxevuHYkKaO6GtEaCHzExhai/QJ8T1QYhrBHiCK1OW1lucHWoNQl0jQBVt5NeUpJS972JKFSGuESCPiSlJ5wG/TyQDhFoE2N9qsntNGnIBQ0JfH4RehHbmn9hu1Bnjap6vBxqEXgQ41ly7E9HtuL9eaFAPRIBRxm5LPoAjyNy7pv0l1HcNO3ua3Xm7ntQH9aJGADjFIqaIVA9SZzP1RIRRNPMcM57W9aY+qDcidDJjPEYM5JJ6pEG9EQGPqxZgk98ZzjD1RgSlblQEBVARFAcVQQFUBMVBRVAAFUFxUBEUQEVQHFQEBVARFAcVQQFUBMVBRVAAFUFxUBEUQEVQHFQEBVARFAcVQQFUBMVBRVAAFUFxUBEUQEVQHFQEBVARFAcVQQFUBMVBRVAAFUFxUBEUQEVQHFQEBVARFAcVQQFUBMVBRVAAFUFxUBEUQEVQHFQEBVARFAcVQQFUBMVBRVAAFUFxUBEUQEVQHFQEBVARFAcVQQFUBMVBRVAAFUFxUBEUQEVQHFQEBVARFAcVQQFUBMVBRVAAFUFxUBEUQEVQHFQEBVARFAcVQQFUBMVBRVAAFUFxUBEUQEVQHFQEBahHIlR6/HyF3xnOMA38zkCmOJyLyMEk+elyTvQ7wxnGiN85ULKCetM0KHWjIiiAiqA4qAgKoCIoDiqCAqgIioOKoAAqguKgIiiAiqA4qAgKoCIoDiqCAqgIioOKoAAqguKgIiiAiqA4qAgKoCIoDiqCAsD/A5S7gmsXJkUHAAAAAElFTkSuQmCC
repository: yantrashala/yantrashala.github.io # ex. DONGChuan/DONGChuan.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: http://localhost:4000

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  syntax_highlighter: true

# Disque
disque: my_disque_settings # ex. httpdongchuangithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: Home

  -
    href: /
    label: Blog

  -
    href: /
    label: Bookmark

  -
    href: /
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'tracking_id'  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, C, C++, Qt, Python, MySQL, Oracle, SQLite, PL/SQL, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, AngularJS, NodeJS, ExpressJS, MongoDB, Redis, PHP, Symfony, Boostrap]
skill_mobile_app_keywords: [Android, Sketch UI Desgin]
